env:
   global:
    - SECRET_KEY_BASE=c068c0175cf596dc06cf0346aff3253a041cd14c1b50e1b2041590a4f83c2e72d46352510969be147098aeb3cf39b4b411f8ede9d5c61dc09cfae317b2d57e31
language: ruby
rvm:
 - 2.3.4
os:
 - linux
env:
   global:
    - BUNDLE_JOBS=4
before_script:
 - cp -f config/secret_env.yml config/secrets.yml
 - psql -c "CREATE ROLE dneslov WITH SUPERUSER CREATEDB LOGIN PASSWORD '';" -U postgres
 - bundle exec rake db:create db:migrate
