dist: xenial
language: ruby
postgresql: 9.5
rvm:
 - 2.5.1
env:
   global:
    - BUNDLE_JOBS=4

addons:
   apt_packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - postgresql-client-9.5
    - libqtwebkit-dev
    - libqtwebkit4

before_script:
 - gem update --system
 - gem --version
 - gem install bundler
 - psql -c 'create database dneslov;' -U postgres
 - bundle exec rake db:migrate
 - ./cc-test-reporter before-build

before_install:
 - bundle install
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter

script:
 - bundle exec rake cucumber
 - bundle audit

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
